version: '3'
include:
  - ./database/docker-compose.yaml
services:
  backend:
    image: backend
    build:
      context: ./backend
    container_name: backend
    restart: always
    environment:
      ID: 11111
    ports:
      - "9100:9100"
    depends_on:
      - nginx