version: '3'
services:
  master:
    build:
      context: ./config-master
      args:
        server_id: 11111
    container_name: master
    restart: always
    volumes:
      - ./config-master/data:/var/lib/mysql
    #  - ./config-master/my.cnf:/etc/mysql/my.cnf
      - ./config-master/log:/var/log/mysql
      - ./config-master/init:/docker-entrypoint-initdb.d
    environment:
      ID: 11111
    ports:
      - "1111:3306"

  slave1:
    build:
      context: ./config-slave
      args:
        server_id: 22222
    container_name: slave1
    restart: always
    volumes:
      - ./config-slave/data1:/var/lib/mysql
      - ./config-slave/log:/var/log/mysql
    #  - ./config-slave/my.cnf:/etc/mysql/my.cnf
      - ./config-slave/init:/docker-entrypoint-initdb.d
    environment:
      ID: 22222
    ports:
      - "22222:3306"
    depends_on:
      - master

  slave2:
    build:
      context: ./config-slave
      args:
        server_id: 33333
    container_name: slave2
    restart: always
    volumes:
      - ./config-slave/data2:/var/lib/mysql
      - ./config-slave/log:/var/log/mysql
    #  - ./config-slave/my.cnf:/etc/mysql/my.cnf
      - ./config-slave/init:/docker-entrypoint-initdb.d
    environment:
      ID: 33333
    ports:
      - "33333:3306"
    depends_on:
      - master

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOSTS: master,slave1,slave2
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    depends_on:
      - master

  # backend:
  #   build:
  #     context: ./backend
  #   container_name: backend
  #   restart: always
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://nginx:80/CAR_RENTAL
  #     - SPRING_DATASOURCE_USERNAME=RIOSB
  #     - SPRING_DATASOURCE_PASSWORD=TEST
  #   ports:
  #     - "9000:8080"
  #   depends_on:
  #     - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-log:/var/log/nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - master
