version: '3'
services:
  master:
    build:
      context: ./config-master
      args:
        server_id: 11111
    container_name: master
    restart: always
    volumes:
      - ./config-master/data:/var/lib/mysql
    #  - ./config-master/my.cnf:/etc/mysql/my.cnf
      - ./config-master/init:/docker-entrypoint-initdb.d
    environment:
      ID: 11111
    ports:
      - "1111:3306"

  slave1:
    build:
      context: ./config-slave
      args:
        server_id: 22222
    container_name: slave1
    restart: always
    volumes:
      - ./config-slave/data1:/var/lib/mysql
    #  - ./config-slave/my.cnf:/etc/mysql/my.cnf
      - ./config-slave/init:/docker-entrypoint-initdb.d
    environment:
      ID: 22222
    ports:
      - "22222:3306"
    depends_on:
      - master

  slave2:
    build:
      context: ./config-slave
      args:
        server_id: 33333
    container_name: slave2
    restart: always
    volumes:
      - ./config-slave/data2:/var/lib/mysql
    #  - ./config-slave/my.cnf:/etc/mysql/my.cnf
      - ./config-slave/init:/docker-entrypoint-initdb.d
    environment:
      ID: 33333
    ports:
      - "33333:3306"
    depends_on:
      - master

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - master
      - slave1
      - slave2
