CREATE USER 'replica_user'@'%' IDENTIFIED BY 'password';
GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
SHOW MASTER STATUS;

CREATE USER 'administrator'@'%' IDENTIFIED BY 'TEST';
GRANT ALL PRIVILEGES ON *.* TO 'administrator'@'%';
FLUSH PRIVILEGES;

CREATE USER 'client'@'%' IDENTIFIED BY 'TEST';
GRANT INSERT, SELECT, UPDATE, DELETE ON CAR_RENTAL.* TO 'client'@'%';
FLUSH PRIVILEGES;